# Generated by Django 6.0.1 on 2026-01-08 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='食物名称')),
                ('meal_type', models.CharField(choices=[('breakfast', '早餐'), ('lunch', '午餐'), ('dinner', '晚餐')], max_length=20, verbose_name='餐点类型')),
                ('image', models.ImageField(blank=True, null=True, upload_to='foods/', verbose_name='图片')),
                ('description', models.TextField(blank=True, max_length=200, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '食物项目',
                'verbose_name_plural': '食物项目',
                'ordering': ['meal_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000, verbose_name='内容')),
                ('category', models.CharField(choices=[('complaint', '投诉'), ('suggestion', '建议'), ('praise', '表扬')], default='suggestion', max_length=20, verbose_name='类别')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_public', models.BooleanField(default=True, verbose_name='是否公开')),
                ('is_processed', models.BooleanField(default=False, verbose_name='是否已处理')),
                ('contact_info', models.CharField(blank=True, max_length=100, verbose_name='联系方式')),
                ('admin_note', models.TextField(blank=True, verbose_name='管理员备注')),
            ],
            options={
                'verbose_name': '意见建议',
                'verbose_name_plural': '意见建议',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('voted_at', models.DateTimeField(auto_now_add=True, verbose_name='投票时间')),
                ('vote_for_date', models.DateField(verbose_name='投票日期')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.fooditem', verbose_name='食物')),
            ],
            options={
                'verbose_name': '投票记录',
                'verbose_name_plural': '投票记录',
                'ordering': ['-voted_at'],
                'unique_together': {('food', 'ip_address', 'vote_for_date')},
            },
        ),
    ]
